### ISSUE TITLE
Update to v1.026

### ISSUE THREAD

**Issue by rappoccio** [cms-externals/fastjet-contrib#10]
Hi, Folks,

I would like to update this external to 1.026. The code is there but I need a v1.026 branch to make a PR.

https://github.com/rappoccio/fastjet-contrib/tree/cms/v1.026-patch

Cheers,
Sal

**Comment by Dr15Jones** [comment]
No obvious thread-safety problems with this change.

**Comment by slava77** [comment]
this was requested for 910pre3.
Do we have a testable cmsdist PR for this fastjet-contrib?

**Comment by davidlange6** [comment]
@smuzaffar @iahmad-khan - do you know the best way to copy over the 1.26 branch?
(and reminding of a related old issue https://github.com/cms-sw/cmsdist/issues/2686)

**Comment by iahmad-khan** [comment]
Branch cms/v1.026 created.

**Comment by rappoccio** [comment]
Can we get a 1.026 branch for me to submit a PR today so we can make 9.1.0?

**Comment by iahmad-khan** [comment]
@rappoccio please create a PR against the branch cms/v1.026 i just created.

**Comment by rappoccio** [comment]
Can this be forked off the master? I forked from there. Otherwise I will replay my changes on top of this (rootless) branch.

**Comment by smuzaffar** [comment]
We directly dump sources (using their tar files) in to our cms/v* branches. I am afraid, you havwe to reply your changes on top of  cms/v1.026

**Comment by rappoccio** [comment]
Done. Will close this.
