### ISSUE TITLE
memory leak in fastjet::contrib::EnergyCorrelatorGeneralized v1.032

### ISSUE THREAD

**Issue by slava77** [cms-externals/fastjet-contrib#14]
https://github.com/cms-externals/fastjet-contrib/blob/cms/v1.032/EnergyCorrelator/EnergyCorrelator.cc#L87

https://github.com/cms-externals/fastjet-contrib/blob/cms/v1.032/EnergyCorrelator/EnergyCorrelator.cc#L247

new are never deleted.
This adds up to 70MB on 1K events and I think that it can be a big problem for production if to is not fixed.

I think that we can patch this locally rather than waiting for the upstream to fix it.

@rappoccio @fabiocos @perrotta

**Comment by slava77** [comment]
@fabiocos @smuzaffar 
please confirm that v1.032 is only in 10_1_X

**Comment by fabiocos** [comment]
@slava77 I would say so
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_9_4_X/gcc630/fastjet-contrib.spec
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_0_X/gcc630/fastjet-contrib.spec

contain 1.026

**Comment by slava77** [comment]
OK, then the scope is smaller and we just have to get this fixed in 10_1_X

**Comment by rappoccio** [comment]
I'm traveling this week so I cannot get to this until Monday. 

Cheers,
Sal

**Comment by slava77** [comment]
On 3/7/18 7:59 AM, rappoccio wrote:
> I'm traveling this week so I cannot get to this until Monday.
> 

please pass this to the fastjet-contrib experts

**Comment by slava77** [comment]
I received some details from Lina from fastjet-contrib.
The fix is already available in 1.033.

**Comment by fabiocos** [comment]
@slava77 thanks, we should consider its test and possible integration asap

**Comment by fabiocos** [comment]
@rappoccio could you please verify and confirm that the additions on top of the native v1.032 applied in v1.033 are indeed the desired ones?

Please see https://github.com/cms-externals/fastjet-contrib/pull/16

**Comment by slava77** [comment]
OK, this is resolved now with the update to v1.033, which happened on Mar 12 https://github.com/cms-sw/cmsdist/pull/3830 and should be in 10_1_0pre3
